site_name: "rlbook: joseph-jnl"

site_url: https://joseph-jnl.github.io/rlbook
repo_url: https://github.com/joseph-jnl/rlbook

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          heading_level: 2
          show_root_heading: true
nav:
  - Home: index.md
  - Setup: setup.md
  - Chapters:
    - "2: Multi-armed Bandits": chap2_bandits.md
  - API:
    - Bandits: api_bandits.md
    - Grid Worlds: api_gridworlds.md